### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by wmertens** [cgarvis/react-vendor-prefix#1]
I did `npm install react-vendor-prefix` and then `VP = require('react-vendor-prefix')`. This is what I get:

```
> JSON.stringify(VP.prefix({animation: '0.25 ease'}))
"{"animation":{"0":"0","1":".","2":"2","3":"5","4":" ","5":"e","6":"a","7":"s","8":"e"}}"
```

**Comment by cgarvis** [comment]
Right now it only works if you nest your styles.  I've updated the README
