### ISSUE TITLE
Failing on Jest tests.

### ISSUE THREAD

**Issue by visortelle** [cgarvis/react-vendor-prefix#14]
I use Jest to write tests. It failing on : TypeError: Cannot read property '0' of undefined at eval (node_modules\react-split-pane\node_modules\react-vendor-prefix\dist\index.js:
It happens on this line: `"ms" === t ? t : t[0].toUpperCase() + t.substr(1)`
`!t || "ms" === t ? t : t[0].toUpperCase() + t.substr(1)`Solves the problem.

**Comment by scottburch** [comment]
I just ran into the same thing with Mocha.  I looked at the code and there seems to be a bug.  I would try to fix, but I can't seem to figure out what .OLink is supposed to be.  Did you ever find a solution?

**Comment by scottburch** [comment]
For anyone else who might find this.  I ran into the same issue with Mocha using js-dom.  

I patched it by putting this at the end of my js-dom config stuff.

    const oldGetComputedStyle = window.getComputedStyle
    window.getComputedStyle = (el, s) => {
        const x = oldGetComputedStyle.call(window, el, s);
        x.OLink = '';
        return x;
    };
