### ISSUE TITLE
iOS WebApp Flex

### ISSUE THREAD

**Issue by Schniz** [cgarvis/react-vendor-prefix#3]
this dude does not work on iOS Webapps since the User Agent does not contain the word Safari.

**Comment by G3z** [comment]
i've also just noticed this.
+1

**Comment by G3z** [comment]
i noticed you didn't cover all iOS cases please take a look at https://github.com/cgarvis/react-vendor-prefix/pull/5

**Comment by Schniz** [comment]
Thanks man. Added this to #4
