### ISSUE TITLE
Version needs to be updated

### ISSUE THREAD

**Issue by young** [cgarvis/react-vendor-prefix#7]
The version needs to updated in package.json so NPM will pick up the latest changes.

Right now, if I install via NPM, I'll only pull in the last change since the version was set to 0.0.1 back in February. Every code update needs to be accompanied with a version bump.

Thanks!

**Comment by ericfong** [comment]
+1

**Comment by tlightsky** [comment]
+1

**Comment by young** [comment]
I'm going to close this as we switched to https://github.com/ziad-saab/react-vendor-prefixes/ which is a more updated fork of react-vendor-prefix.
