### ISSUE TITLE
Isomorphic?

### ISSUE THREAD

**Issue by robcolburn** [cgarvis/react-vendor-prefix#9]
Does this break your isomorphic flow?

**Comment by jiyinyiyong** [comment]
In order to support isomorphic rendering we need to parse UA and decide how to prefix properties on a server. That might be hard.

**Comment by robcolburn** [comment]
If you're behind any kind of caching (Varnish, CDN, …) then parsing the UA is a non-starter too.I browsed several module before just writing [a utility script](https://gist.github.com/robcolburn/222ddb43915fbd51a78a) to provide all the prefixed versions all the time.  In practice, this is fairly reasonable since we only use a few style props in JS.
